# .github/actions/setup/action.yaml
name: Set Up Test Environment Action
description: Setup action
runs:
  using: composite
  steps:
    - run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libtool autoconf unzip wget
        sudo apt-get install -y clang-12 make valgrind
        bash ./.github/scripts/install_cmake.sh 3.22 1
      shell: bash
    - run: make --version
      shell: bash
    - run: clang-12 --version
      shell: bash
    - run: cmake --version
      shell: bash
