# .github/actions/setup/action.yaml
name: Set Up Test Environment Action
description: Setup action
runs:
  using: composite
  steps:
    - run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang-12 make
      shell: bash
    - run: make --version
      shell: bash
    - run: valgrind --version
      shell: bash
