// This file is generated by resources/response_code_gen.py
// Do not change it manually

#include "ResponseCodes.h"

const char* http::GetResponseCodeName(ResponseCode rc) {
    switch (rc) {
        case RC_CONTINUE: return "Continue";
        case RC_SWITCHING_PROTOCOLS: return "Switching Protocols";
        case RC_PROCESSING: return "Processing";
        case RC_OK: return "OK";
        case RC_CREATED: return "Created";
        case RC_ACCEPTED: return "Accepted";
        case RC_NON_AUTHORITATIVE_INFORMATION: return "Non-Authoritative Information";
        case RC_NO_CONTENT: return "No Content";
        case RC_RESET_CONTENT: return "Reset Content";
        case RC_PARTIAL_CONTENT: return "Partial Content";
        case RC_MULTI_STATUS: return "Multi-Status";
        case RC_MULTIPLE_CHOICES: return "Multiple Choices";
        case RC_MOVED_PERMANENTLY: return "Moved Permanently";
        case RC_FOUND: return "Found";
        case RC_SEE_OTHER: return "See Other";
        case RC_NOT_MODIFIED: return "Not Modified";
        case RC_USE_PROXY: return "Use Proxy";
        case RC_TEMPORARY_REDIRECT: return "Temporary Redirect";
        case RC_PERMANENT_REDIRECT: return "Permanent Redirect";
        case RC_BAD_REQUEST: return "Bad Request";
        case RC_UNAUTHORIZED: return "Unauthorized";
        case RC_PAYMENT_REQUIRED: return "Payment Required";
        case RC_FORBIDDEN: return "Forbidden";
        case RC_NOT_FOUND: return "Not Found";
        case RC_METHOD_NOT_ALLOWED: return "Method Not Allowed";
        case RC_NOT_ACCEPTABLE: return "Not Acceptable";
        case RC_PROXY_AUTHENTICATION_REQUIRED: return "Proxy Authentication Required";
        case RC_REQUEST_TIMEOUT: return "Request Timeout";
        case RC_CONFLICT: return "Conflict";
        case RC_GONE: return "Gone";
        case RC_LENGTH_REQUIRED: return "Length Required";
        case RC_PRECONDITION_FAILED: return "Precondition Failed";
        case RC_PAYLOAD_TOO_LARGE: return "Payload Too Large";
        case RC_URI_TOO_LONG: return "URI Too Long";
        case RC_UNSUPPORTED_MEDIA_TYPE: return "Unsupported Media Type";
        case RC_RANGE_NOT_SATISFIABLE: return "Range Not Satisfiable";
        case RC_EXPECTATION_FAILED: return "Expectation Failed";
        case RC_I_M_A_TEAPOT: return "I'm a Teapot";
        case RC_UNPROCESSABLE_ENTITY: return "Unprocessable Entity";
        case RC_LOCKED: return "Locked";
        case RC_FAILED_DEPENDENCY: return "Failed Dependency";
        case RC_UPGRADE_REQUIRED: return "Upgrade Required";
        case RC_PRECONDITION_REQUIRED: return "Precondition Required";
        case RC_TOO_MANY_REQUESTS: return "Too Many Requests";
        case RC_REQUEST_HEADER_FIELDS_TOO_LARGE: return "Request Header Fields Too Large";
        case RC_UNAVAILABLE_FOR_LEGAL_REASONS: return "Unavailable For Legal Reasons";
        case RC_INTERNAL_SERVER_ERROR: return "Internal Server Error";
        case RC_NOT_IMPLEMENTED: return "Not Implemented";
        case RC_BAD_GATEWAY: return "Bad Gateway";
        case RC_SERVICE_UNAVAILABLE: return "Service Unavailable";
        case RC_GATEWAY_TIMEOUT: return "Gateway Timeout";
        case RC_HTTP_VERSION_NOT_SUPPORTED: return "HTTP Version Not Supported";
        case RC_VARIANT_ALSO_NEGOTIATES: return "Variant Also Negotiates";
        case RC_INSUFFICIENT_STORAGE: return "Insufficient Storage";
        case RC_LOOP_DETECTED: return "Loop Detected";
        case RC_NOT_EXTENDED: return "Not Extended";
        case RC_NETWORK_AUTHENTICATION_REQUIRED: return "Network Authentication Required";
        default: return "Unknown";
    }
}
