# .github/workflows/ci_workflow.yaml
name: CI Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - main

env:
  HOME: /home/runner

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Title Format
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '\[[A-Z]+\] \S.*'
          error: 'PR title hast to start with a commit type - for example [REFACTOR] - followed by a description".'
          excludeDescription: 'false'  # Check the entire commit message
          excludeTitle: 'false'  # Do not exclude the title
          checkAllCommitMessages: 'false'  # Check only the PR title, assuming it's the first commit
        if: github.event_name == 'pull_request' && !contains(github.event.pull_request.title, 'Merge pull request') && !contains(github.event.pull_request.title, 'Merge branch')
      - name: Check Last Commit Message Format
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^([a-z]+)(?:\([^\)]*\))?(?:!)?: \S.*|^Merge pull request #[0-9]+ from [\w\-]+\/[\w\-].*'
          error: 'Commit messages must follow the format "<type>[(optional scope)][!]: <description>.". See https://stackoverflow.com/questions/8981194/changing-git-commit-message-after-push-given-that-no-one-pulled-from-remote for renames
          excludeDescription: 'true' # optional: this excludes the description body of a pull request
          excludeTitle: 'true' # optional: this excludes the title of a pull request
          checkAllCommitMessages: 'true' # optional: this checks all commits associated with a pull request
      - name: Check Last Commit Message Length
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^.{0,100}$'
          error: 'The last commit message cannot be longer than 100 characters.'
          excludeDescription: 'true' # optional: this excludes the description body of a pull request
          excludeTitle: 'true' # optional: this excludes the title of a pull request
          checkAllCommitMessages: 'false' # optional: this checks all commits associated with a pull request
          # accessToken: ${{ secrets.GITHUB_TOKEN }} # github access token is only required if checkAllCommitMessages is true
        if: (!contains(github.event.pull_request.title, 'Merge pull request') && !contains(github.event.pull_request.title, 'Merge branch'))
  compilation_test:
    name: Compilation Test
    runs-on: ubuntu-latest
    timeout-minutes: 2
    strategy:
      fail-fast: false
    steps:
      - name: Checkout source branch of pull request
        uses: actions/checkout@v4
      - name: Set up test environment
        uses: ./.github/actions/setup
      - name: 🔨 Compile with Makefile
        run: make
  combine_compilation_test_result:
    name: Compilation Test Result
    needs: compilation_test
    runs-on: ubuntu-latest
    steps:
      - name: Show compilation test results
        run: echo "Compilation successful"
